/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['id3.js']) {
  _$jscoverage['id3.js'] = [];
  _$jscoverage['id3.js'][2] = 0;
  _$jscoverage['id3.js'][3] = 0;
  _$jscoverage['id3.js'][5] = 0;
  _$jscoverage['id3.js'][7] = 0;
  _$jscoverage['id3.js'][9] = 0;
  _$jscoverage['id3.js'][11] = 0;
  _$jscoverage['id3.js'][13] = 0;
  _$jscoverage['id3.js'][15] = 0;
  _$jscoverage['id3.js'][17] = 0;
  _$jscoverage['id3.js'][19] = 0;
  _$jscoverage['id3.js'][24] = 0;
  _$jscoverage['id3.js'][29] = 0;
}
_$jscoverage['id3.js'][2]++;
(function () {
  _$jscoverage['id3.js'][3]++;
  var OPTS, Parser, SHORT_OPTS, fs, log, nopt, options, path, util;
  _$jscoverage['id3.js'][5]++;
  require("coffee-script");
  _$jscoverage['id3.js'][7]++;
  fs = require("fs");
  _$jscoverage['id3.js'][9]++;
  path = require("path");
  _$jscoverage['id3.js'][11]++;
  util = require("util");
  _$jscoverage['id3.js'][13]++;
  log = require("npmlog");
  _$jscoverage['id3.js'][15]++;
  nopt = require("nopt");
  _$jscoverage['id3.js'][17]++;
  Parser = require("./parser").Parser;
  _$jscoverage['id3.js'][19]++;
  OPTS = {"file": path, "art_out": path};
  _$jscoverage['id3.js'][24]++;
  SHORT_OPTS = {"f": ["--file"], "a": ["--art_out"]};
  _$jscoverage['id3.js'][29]++;
  options = nopt(OPTS, SHORT_OPTS);
}).call(this);
_$jscoverage['id3.js'].source = ["// Generated by CoffeeScript 1.3.3","(function() {","  var OPTS, Parser, SHORT_OPTS, fs, log, nopt, options, path, util;","","  require('coffee-script');","","  fs = require('fs');","","  path = require('path');","","  util = require('util');","","  log = require('npmlog');","","  nopt = require('nopt');","","  Parser = require('./parser').Parser;","","  OPTS = {","    'file': path,","    'art_out': path","  };","","  SHORT_OPTS = {","    'f': ['--file'],","    'a': ['--art_out']","  };","","  options = nopt(OPTS, SHORT_OPTS);","","}).call(this);"];
