// Generated by CoffeeScript 1.3.3
(function() {
  var OPTS, Parser, SHORT_OPTS, fs, log, nopt, options, path, util;

  require('coffee-script');

  fs = require('fs');

  path = require('path');

  util = require('util');

  log = require('npmlog');

  nopt = require('nopt');

  Parser = require('./parser').Parser;

  OPTS = {
    'file': path,
    'art_out': path
  };

  SHORT_OPTS = {
    'f': ['--file'],
    'a': ['--art_out']
  };

  options = nopt(OPTS, SHORT_OPTS);

}).call(this);
